vim.keymap.set('n', '<leader>ga', ':G add -A<CR>')
vim.keymap.set('n', '<leader>gs', ':G status<CR>')
vim.keymap.set('n', '<leader>gc', ':G commit<CR>')
vim.keymap.set('n', '<leader>gd', ':Gdiff<CR>')
vim.keymap.set('n', '<leader>ge', ':Gedit<CR>')
vim.keymap.set('n', '<leader>gr', ':Gread<CR>')
vim.keymap.set('n', '<leader>gw', ':Gwrite<CR>')
vim.keymap.set('n', '<leader>gp', ':G push<CR>')
vim.keymap.set('n', '<leader>gm', ':Gmove<Space>')
vim.keymap.set('n', '<leader>gb', ':Git branch<Space>')
vim.keymap.set('n', '<leader>go', ':Git checkout<Space>')
vim.keymap.set('n', '<leader>gps', ':Dispatch! git push<CR>')
vim.keymap.set('n', '<leader>gpl', ':Dispatch! git pull<CR>')
